#Alacritty Configuration

# The Configuration is broken down into [table]
# each table houses values which are set with
# integers or string values for customization.
# For additional help see the following
# https://alacritty.org/config-alacritty.html

# GENERAL
	import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]
	shell = { program = "/bin/zsh", args = [] } # Default shell is system-dependent
	working_directory = "/home/hunterca"
	live_config_reload = true

# ENV
[env]

# WINDOW
[window]
	dimensions = { columns = 0, lines = 0 }
	position = "None"
	padding = { x = 0, y = 0 }
	dynamic_padding = false
	decorations = "Full"
	opacity = 0.90
	blur = true # macOS/KDE Wayland only
	startup_mode = "Windowed"
	title = "Alacritty"
	dynamic_title = true
	class = { instance = "Alacritty", general = "Alacritty" }
	decorations_theme_variant = "None"
	resize_increments = false

# SCROLLING
[scrolling]
	history = 10000
	multiplier = 3

# FONT
[font]
	normal = { family = "MesloLGS NF", style = "Regular" }
	bold = { style = "MesloLGS NF Bold" }
	italic = { style = "MesloLGS NF Italic" }
	bold_italic = { style = "MesloLGS NF Bold Italic" }
	size = 11.25
	offset = { x = 0, y = 0 }

# Colors Controlled by alacritty-themes


# BELL
[bell]
	animation = "Linear"
	duration = 0
	color = "#ffffff"
	command = "None"

# SELECTION
[selection]
	semantic_escape_chars = ",│`|:\"' ()[]{}<>t"
	save_to_clipboard = false

# CURSOR
[cursor]
	style = { shape = "Underline", blinking = "On" }
	vi_mode_style = "None"
	blink_interval = 650
	blink_timeout = 5
	unfocused_hollow = true
	thickness = 0.15

# TERMINAL
[terminal]
	osc52 = "OnlyCopy"

# MOUSE
[mouse]
	hide_when_typing = false
	bindings = []

# HINTS
[hints]
	alphabet = "jfkdls;ahgurieowpq"
	enabled = []

# KEYBOARD
[keyboard]
	bindings = []

# DEBUG
[debug]
	render_timer = false
	persistent_logging = false
	log_level = "Warn"
	renderer = "None"
	print_events = false
	highlight_damage = false
	prefer_egl = false

